require:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2

  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/*.rb'
  Exclude:
    - 'Capfile'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'stubs/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'features/step_definitions/*'
    - 'app/views/**/*.jbuilder'

  NewCops: enable

# Checks formatting of special comments
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

########################################
# Style Cops

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# String#format is private now
Style/FormatString:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

########################################
# Layout Cops

Layout/LineLength:
  Max: 110
  Exclude:
    - 'app/views/**/*'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: table

Layout/AssignmentIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/CaseIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

########################################
# Naming Cops

Naming/FileName:
  Enabled: false

########################################
# Security Cops

Security/Eval:
  Enabled: true

########################################
# Lint Cops

Lint/AssignmentInCondition:
  Enabled: false

########################################
# Metrics Cops

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 20

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - lib/tasks/**/*.rake
    - config/routes.rb
    - config/environments/*.rb

########################################
# Rspec Cops

RSpec/MultipleExpectations:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false


########################################
# Rails Cops

Rails/I18nLocaleTexts:
  Enabled: false

########################################
# Bundler Cops

Bundler/OrderedGems:
  Enabled: false

########################################
# New Cops

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Lint/EmptyInPattern: # (new in 1.16)
  Enabled: true
Style/InPatternThen: # (new in 1.16)
  Enabled: true
Style/MultilineInPatternThen: # (new in 1.16)
  Enabled: true
Style/QuotedSymbols: # (new in 1.16)
  Enabled: true
